name: Yassen
favicon: null
layout_spectrum: 0.37613
typography_spectrum: 0.6004357561469078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ababab'
    - '#4c4c4c'
    - '#242424'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
